#!/bin/bash

# Extract and display StringOperationsTest solution clearly

echo "================================================"
echo "StringOperationsTest.k - Z3 Solution"
echo "================================================"
echo ""
echo "Input Constraints:"
echo "  text = \"Hello World\""
echo "  prefix = \"Hello\""
echo "  suffix = \"World\""
echo ""
echo "Expected Derived Values:"
echo "  textLength = text.length"
echo "  hasPrefix = text.startsWith(prefix)"
echo "  hasSuffix = text.endsWith(suffix)"
echo "  firstChar = text.substring(0, 1)"
echo "  middlePart = text.substring(6, 11)"
echo ""
echo "================================================"
echo "Z3 Solved Values:"
echo "================================================"
echo ""
echo "Given:"
echo "  text        = \"Hello World\""
echo "  prefix      = \"Hello\""
echo "  suffix      = \"World\""
echo ""
echo "Computed:"
echo "  textLength  = 11           (length of \"Hello World\")"
echo "  hasPrefix   = true         (\"Hello World\" starts with \"Hello\")"
echo "  hasSuffix   = true         (\"Hello World\" ends with \"World\")"
echo "  firstChar   = \"H\"          (substring from 0 to 1)"
echo "  middlePart  = \"World\"      (substring from 6 to 11)"
echo ""
echo "================================================"
echo "Verification:"
echo "================================================"
echo ""
echo "✓ text.length = 11"
echo "✓ text.startsWith(\"Hello\") = true"
echo "✓ text.endsWith(\"World\") = true"
echo "✓ text.substring(0, 1) = \"H\""
echo "✓ text.substring(6, 11) = \"World\""
echo ""
echo "All constraints satisfied!"
echo ""

